2020-10-13 12:09:14,476	INFO services.py:1164 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
== Status ==
Memory usage on this node: 11.5/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 80/80 CPUs, 0/3 GPUs, 0.0/558.35 GiB heap, 0.0/128.52 GiB objects (0/1.0 accelerator_type:RTX)
Result logdir: /root/ray_results/ppo-jss
Number of trials: 1 (1 RUNNING)
+----------------------------------+----------+-------+
| Trial name                       | status   | loc   |
|----------------------------------+----------+-------|
| RandomMasked_jss_env_e9d96_00000 | RUNNING  |       |
+----------------------------------+----------+-------+


[2m[36m(pid=539)[0m 2020-10-13 12:09:17,107	INFO trainer.py:616 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2020-10-13 12:09:21,656	ERROR trial_runner.py:567 -- Trial RandomMasked_jss_env_e9d96_00000: Error processing event.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::RandomMasked.train()[39m (pid=539, ip=172.17.0.4)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 519, in train
    raise e
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    result = Trainable.train(self)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 134, in step
    res = next(self.train_exec_impl)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/execution/metric_ops.py", line 83, in __call__
    episodes.extend(self.episode_history[-missing:])
TypeError: slice indices must be integers or None or have an __index__ method
== Status ==
Memory usage on this node: 21.9/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/80 CPUs, 0/3 GPUs, 0.0/558.35 GiB heap, 0.0/128.52 GiB objects (0/1.0 accelerator_type:RTX)
Result logdir: /root/ray_results/ppo-jss
Number of trials: 1 (1 ERROR)
+----------------------------------+----------+-------+
| Trial name                       | status   | loc   |
|----------------------------------+----------+-------|
| RandomMasked_jss_env_e9d96_00000 | ERROR    |       |
+----------------------------------+----------+-------+
Number of errored trials: 1
+----------------------------------+--------------+--------------------------------------------------------------------------------------------+
| Trial name                       |   # failures | error file                                                                                 |
|----------------------------------+--------------+--------------------------------------------------------------------------------------------|
| RandomMasked_jss_env_e9d96_00000 |            1 | /root/ray_results/ppo-jss/RandomMasked_jss_env_e9d96_00000_0_2020-10-13_12-09-15/error.txt |
+----------------------------------+--------------+--------------------------------------------------------------------------------------------+

== Status ==
Memory usage on this node: 21.9/754.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/80 CPUs, 0/3 GPUs, 0.0/558.35 GiB heap, 0.0/128.52 GiB objects (0/1.0 accelerator_type:RTX)
Result logdir: /root/ray_results/ppo-jss
Number of trials: 1 (1 ERROR)
+----------------------------------+----------+-------+
| Trial name                       | status   | loc   |
|----------------------------------+----------+-------|
| RandomMasked_jss_env_e9d96_00000 | ERROR    |       |
+----------------------------------+----------+-------+
Number of errored trials: 1
+----------------------------------+--------------+--------------------------------------------------------------------------------------------+
| Trial name                       |   # failures | error file                                                                                 |
|----------------------------------+--------------+--------------------------------------------------------------------------------------------|
| RandomMasked_jss_env_e9d96_00000 |            1 | /root/ray_results/ppo-jss/RandomMasked_jss_env_e9d96_00000_0_2020-10-13_12-09-15/error.txt |
+----------------------------------+--------------+--------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "random_loop.py", line 72, in <module>
    rand_func()
  File "random_loop.py", line 54, in rand_func
    analysis = tune.run(RandomMaskedTrainer, config=config, stop=stop, name="ppo-jss")
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/tune.py", line 427, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [RandomMasked_jss_env_e9d96_00000])
