2020-12-18 16:21:36,762 INFO    MainThread:72213 [wandb_setup.py:_flush():70] setting env: {}
2020-12-18 16:21:36,762 INFO    MainThread:72213 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-18 16:21:36,762 INFO    MainThread:72213 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-18 16:21:36,762 INFO    MainThread:72213 [wandb_init.py:_log_setup():303] Logging user logs to /home/jupyter/JSS/JSS/wandb/run-20201218_162136-1c9rhd6j/logs/debug.log
2020-12-18 16:21:36,763 INFO    MainThread:72213 [wandb_init.py:_log_setup():304] Logging internal logs to /home/jupyter/JSS/JSS/wandb/run-20201218_162136-1c9rhd6j/logs/debug-internal.log
2020-12-18 16:21:38,160 INFO    MainThread:72213 [wandb_run.py:_console_start():1237] atexit reg
2020-12-18 16:21:38,161 INFO    MainThread:72213 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-18 16:21:38,162 INFO    MainThread:72213 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-18 16:21:38,162 INFO    MainThread:72213 [redirect.py:install():204] install start
2020-12-18 16:21:38,163 INFO    MainThread:72213 [redirect.py:install():219] install stop
2020-12-18 16:21:38,163 INFO    MainThread:72213 [redirect.py:install():204] install start
2020-12-18 16:21:38,163 INFO    MainThread:72213 [redirect.py:install():219] install stop
2020-12-18 16:21:38,164 INFO    MainThread:72213 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-18 16:21:41,263 INFO    MainThread:72213 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-18 16:21:41,265 INFO    MainThread:72213 [wandb_run.py:_restore():1179] restore
2020-12-18 16:21:41,265 INFO    MainThread:72213 [redirect.py:uninstall():223] uninstall start
2020-12-18 16:21:41,266 INFO    MainThread:72213 [redirect.py:_stop():278] _stop: stdout
2020-12-18 16:21:41,267 INFO    MainThread:72213 [redirect.py:_stop():284] _stop closed: stdout
2020-12-18 16:21:41,267 INFO    stdout    :72213 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-18 16:21:41,268 INFO    stdout    :72213 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-18 16:21:41,268 INFO    MainThread:72213 [redirect.py:_stop():290] _stop joined: stdout
2020-12-18 16:21:41,268 INFO    MainThread:72213 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-18 16:21:41,269 INFO    MainThread:72213 [redirect.py:uninstall():227] uninstall done
2020-12-18 16:21:41,269 INFO    MainThread:72213 [redirect.py:uninstall():223] uninstall start
2020-12-18 16:21:41,269 INFO    MainThread:72213 [redirect.py:_stop():278] _stop: stderr
2020-12-18 16:21:41,269 INFO    MainThread:72213 [redirect.py:_stop():284] _stop closed: stderr
2020-12-18 16:21:41,269 INFO    stderr    :72213 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-18 16:21:41,269 INFO    stderr    :72213 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-18 16:21:41,270 INFO    MainThread:72213 [redirect.py:_stop():290] _stop joined: stderr
2020-12-18 16:21:41,270 INFO    MainThread:72213 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-18 16:21:41,270 INFO    MainThread:72213 [redirect.py:uninstall():227] uninstall done
2020-12-18 16:21:41,274 INFO    MainThread:72213 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "e434f6733c034e60a8a307c4177511e4"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 2
      other_count: 1
    }
    pusher_stats {
      uploaded_bytes: 13044
      total_bytes: 13044
    }
  }
}

2020-12-18 16:21:43,280 INFO    MainThread:72213 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "d52731279b2e4f229469330103f89043"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 6
      other_count: 1
    }
    pusher_stats {
      uploaded_bytes: 23277
      total_bytes: 23277
    }
  }
}

2020-12-18 16:21:44,379 INFO    MainThread:72213 [wandb_run.py:_show_files():1536] logging synced files
2020-12-18 16:21:44,385 INFO    MainThread:72213 [internal.py:handle_exit():138] Internal process exited
