2020-11-30 09:48:36,264	INFO services.py:1104 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
Traceback (most recent call last):
  File "train_wandb.py", line 155, in <module>
    train_func()
  File "train_wandb.py", line 143, in train_func
    trainer = PPOTrainer(config=config)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 566, in setup
    self.config = Trainer.merge_trainer_configs(self._default_config,
  File "/root/miniconda3/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1044, in merge_trainer_configs
    return deep_update(config1, config2, _allow_unknown_configs,
  File "/root/miniconda3/lib/python3.8/site-packages/ray/tune/utils/util.py", line 215, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `activation_fn` 
