2020-12-18 16:22:39,396 INFO    MainThread:73892 [wandb_setup.py:_flush():70] setting env: {}
2020-12-18 16:22:39,396 INFO    MainThread:73892 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-18 16:22:39,396 INFO    MainThread:73892 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-18 16:22:39,396 INFO    MainThread:73892 [wandb_init.py:_log_setup():303] Logging user logs to /home/jupyter/JSS/JSS/wandb/run-20201218_162239-3ouv4pik/logs/debug.log
2020-12-18 16:22:39,397 INFO    MainThread:73892 [wandb_init.py:_log_setup():304] Logging internal logs to /home/jupyter/JSS/JSS/wandb/run-20201218_162239-3ouv4pik/logs/debug-internal.log
2020-12-18 16:22:40,833 INFO    MainThread:73892 [wandb_run.py:_console_start():1237] atexit reg
2020-12-18 16:22:40,834 INFO    MainThread:73892 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-18 16:22:40,835 INFO    MainThread:73892 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-18 16:22:40,835 INFO    MainThread:73892 [redirect.py:install():204] install start
2020-12-18 16:22:40,836 INFO    MainThread:73892 [redirect.py:install():219] install stop
2020-12-18 16:22:40,836 INFO    MainThread:73892 [redirect.py:install():204] install start
2020-12-18 16:22:40,837 INFO    MainThread:73892 [redirect.py:install():219] install stop
2020-12-18 16:22:40,837 INFO    MainThread:73892 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-18 16:22:43,860 INFO    MainThread:73892 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-18 16:22:43,862 INFO    MainThread:73892 [wandb_run.py:_restore():1179] restore
2020-12-18 16:22:43,862 INFO    MainThread:73892 [redirect.py:uninstall():223] uninstall start
2020-12-18 16:22:43,862 INFO    MainThread:73892 [redirect.py:_stop():278] _stop: stdout
2020-12-18 16:22:43,863 INFO    MainThread:73892 [redirect.py:_stop():284] _stop closed: stdout
2020-12-18 16:22:43,863 INFO    stdout    :73892 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-18 16:22:43,864 INFO    stdout    :73892 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-18 16:22:43,864 INFO    MainThread:73892 [redirect.py:_stop():290] _stop joined: stdout
2020-12-18 16:22:43,864 INFO    MainThread:73892 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-18 16:22:43,864 INFO    MainThread:73892 [redirect.py:uninstall():227] uninstall done
2020-12-18 16:22:43,865 INFO    MainThread:73892 [redirect.py:uninstall():223] uninstall start
2020-12-18 16:22:43,865 INFO    MainThread:73892 [redirect.py:_stop():278] _stop: stderr
2020-12-18 16:22:43,865 INFO    MainThread:73892 [redirect.py:_stop():284] _stop closed: stderr
2020-12-18 16:22:43,865 INFO    stderr    :73892 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-18 16:22:43,865 INFO    stderr    :73892 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-18 16:22:43,865 INFO    MainThread:73892 [redirect.py:_stop():290] _stop joined: stderr
2020-12-18 16:22:43,866 INFO    MainThread:73892 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-18 16:22:43,866 INFO    MainThread:73892 [redirect.py:uninstall():227] uninstall done
2020-12-18 16:22:43,870 INFO    MainThread:73892 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "4bc2312a58154423b869cb4e9b75cd51"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 2
      other_count: 1
    }
    pusher_stats {
      uploaded_bytes: 14391
      total_bytes: 14391
    }
  }
}

2020-12-18 16:22:45,874 INFO    MainThread:73892 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "df8bc53b7be241188fa0e49fa4465e2e"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 6
      other_count: 1
    }
    pusher_stats {
      uploaded_bytes: 24624
      total_bytes: 24624
    }
  }
}

2020-12-18 16:22:46,974 INFO    MainThread:73892 [wandb_run.py:_show_files():1536] logging synced files
2020-12-18 16:22:46,981 INFO    MainThread:73892 [internal.py:handle_exit():138] Internal process exited
